[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --color=yes
markers =
    smoke: Быстрые ключевые тесты
    regression: Полная регрессия
    api: Тесты Api
    negative: Негативные тесты(проверка на ошибки)
